version: "3.8"
services:
  slate-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: slate-server
    image: slate-server
    restart: unless-stopped
    ports:
      - "1234:1234"
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
